#ifndef _FUNCONFIG_H
#define _FUNCONFIG_H

#define CH32V20x                 1
#define CH32V208 1
#define CH32V20x_D8W 1
#define FUNCONF_SYSTICK_USE_HCLK 1
#define FUNCONF_USE_HSI          1
#define FUNCONF_SYSTEM_CORE_CLOCK 120000000
#define FUNCONF_ENABLE_HPE 1 
#define FUNCONF_TINYVECTOR 1 

#define FUNCONF_DEBUG_HARDFAULT 0

#endif
